version: "3.7"
services:
  webapp:
    build: .
    volumes:
      - "./config/logstash/:/usr/share/logstash/pipeline/"
  otel:
    image: paulgrav/opentelemetry-collector-contrib:0.42.0
    volumes:
      - "./config/otel/otel.yaml:/etc/otel/config.yaml"
