# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Gem

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ARTIFACT_NAME: logstash-output-opentelemetry.zip

jobs:
  build:
    name: build gem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt-hotspot'
    - name: Build with Make and set version
      if: ${{ github.ref_type == 'tag' }}
      run: make gem VERSION=$VERSION
      shell: bash
      env:
        VERSION: ${{ github.ref_name }}
    - name: Build with Make
      if: ${{ github.ref_type != 'tag' }}
      run: make gem
      shell: bash
  test:
    name: test gem
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: logstash:7.10.1
      ports:
        - 80
      volumes:
        - "config/logstash/:/usr/share/logstash/pipeline/"
      options: --cpus 1
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
    - name: Run check end
      run: ls -lt
    - name: install
      run: docker run otel/opentelemetry-collector:0.42.0 -v config/otel/otel.yaml:/etc/otel/config.yaml -p 4317:4317
    - name: check otel
      run: docker ps
    - name: Install logstash
      run: logstash-plugin install --no-verify --local /files/*gem
      shell: bash
    - name: Archive gem artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME  }}
        path: |
          *.gem
          VERSION



